name = "video-render-cloudflare"
main = "worker/index.js"
compatibility_date = "2026-06-10"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "JOBS"
id = "replace_with_cloudflare_kv_namespace_id"
